### ISSUE TITLE
[Feature] Parse Solidity types and values from yaml file

### ISSUE THREAD

**Issue by quangkeu95** [quangkeu95/tudo#6]
# Components
tudo-interpreter

# Describe the feature
So in the yaml file, we have some definitions like:
```yaml
function_arguments:
  - type: uint
     value: 10000
  - type: bool
     value: true
```

We want the function arguments will be parsed into an `Vec<FunctionArgument>` where each `FunctionArgument` contains the Solidity type and the value of that argument. `FunctionArgument` should be able to convert into `Bytes` so we can combine arguments into a calldata.

We could use an enum to represent Solidity types.

# Additional contexts
